### PR TITLE
Micro-Reddit

### PR DESCRIPTION
**Pull request by Godswilly**
In this project, I worked on the Rails Active Record Model
1. I built models for:
- User
- Post
- Comment 
2. Validated them
3.Linked them through association

### CODE REVIEW

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
## Status: Request changes :recycle:
### Hi @Godswilly :clap: :clap:
#### You have done a good job :+1: However, you need to add tests.

* [ ] **_A user can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingUser.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))_**
* [ ] **_A post can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingPost.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))_**
* [ ] **_A comment can be created **(covered by automated tests)** ([screenshot](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/building_with_active_record/creatingComment.png) from [Odin Project](https://www.theodinproject.com/courses/ruby-on-rails/lessons/building-with-active-record-ruby-on-rails))_**

- **_Add tests for each model and remember to include the association between each model in the tests._**

#### _Reviewed by Temitayo Adeleke._

**Comment by Godswilly** [comment]
Honestly, I checked pathwright again for the requirements on this project just to be sure that the tests the TSE requested I should add is not in the requirements. I have tried reaching out to him on slack since yesterday but no response yet. Every other thing is working fine in the project to the best of my knowledge.

**Review by peterrobert — CHANGES_REQUESTED** [review]
### CHANGES REQUIRED :recycle: :stop_sign: 
### HELLO @Godswilly NICE PROGRESS SO FAR I CAN SEE THAT YOU HAVE CREATED THE MIGRATIONS AND THE MODELS :+1: HOWEVER, THERE ARE AFEW THINGS THAT NEEDS TO BE DONE.

- [ ] A user can be created. Just as suggested in the previous review this is actually a requirement. :arrow_down: 
creatingUser

- [ ] A post can be created. :arrow_down: 
creatingPost

- [ ] A comment can be created. This is also a requirement. :arrow_down: 
creatingComment

Kindly you need to create this in your project.

### if you have any question kindly reach me on slack @peterrobert

### HAPPY CODING :computer:

**Comment by Godswilly** [comment]
Please I want to state it emphatically that all the changes the previous TSE's requested are already working in the project.

**Review by rOluochKe — APPROVED** [review]
Hello @Godswilly 
### You did well, you got it right :clap: The project has been approved. Congratulations :boom: :100:
### Merge and submit the project. Good luck with the next one.
- Happy coding!

**Pull request merged**
